import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import Menu from "@/components/page/layout/menu"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative h-full">
          <nav className="relative flex items-center p-3 border-b">
            <Menu />
            <h1 className="absolute left-0 right-0 text-3xl font-semibold text-center -z-10">GDCM</h1>
          </nav>
          <section className="p-4 sm:container sm:py-6">
            {children}
          </section>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
